### ISSUE TITLE
docker-compose example is not working

### ISSUE THREAD

**Issue by amalic** [SANSA-Stack/SANSA-RDF#21]
docker logs namenode
```
17/11/06 12:23:33 WARN blockmanagement.DatanodeManager: Unresolved datanode registration: hostname cannot be resolved (ip=172.18.0.1, hostname=172.18.0.1)
17/11/06 12:23:33 INFO ipc.Server: IPC Server handler 7 on 8020, call org.apache.hadoop.hdfs.server.protocol.DatanodeProtocol.registerDatanode from 172.18.0.1:40794 Call#89 Retry#0
org.apache.hadoop.hdfs.server.protocol.DisallowedDatanodeException: Datanode denied communication with namenode because hostname cannot be resolved (ip=172.18.0.1, hostname=172.18.0.1): DatanodeRegistration(0.0.0.0:50010, datanodeUuid=da77cef5-2125-42ee-87f6-1fbd6acf95ee, infoPort=50075, infoSecurePort=0, ipcPort=50020, storageInfo=lv=-56;cid=CID-2d669e73-96e6-4bbf-bb55-678919083f6c;nsid=1537263042;c=0)
        at org.apache.hadoop.hdfs.server.blockmanagement.DatanodeManager.registerDatanode(DatanodeManager.java:863)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.registerDatanode(FSNamesystem.java:4529)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.registerDatanode(NameNodeRpcServer.java:1279)
        at org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolServerSideTranslatorPB.registerDatanode(DatanodeProtocolServerSideTranslatorPB.java:95)
        at org.apache.hadoop.hdfs.protocol.proto.DatanodeProtocolProtos$DatanodeProtocolService$2.callBlockingMethod(DatanodeProtocolProtos.java:28539)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)
```

docker logs datanode1
```
17/11/06 12:24:13 INFO datanode.DataNode: Block pool BP-988677139-172.18.0.2-1509970722564 (Datanode Uuid null) service to namenode/172.18.0.2:8020 beginning handshake with NN
17/11/06 12:24:13 ERROR datanode.DataNode: Initialization failed for Block pool BP-988677139-172.18.0.2-1509970722564 (Datanode Uuid null) service to namenode/172.18.0.2:8020 Datanode denied communication with namenode because hostname cannot be resolved (ip=172.18.0.1, hostname=172.18.0.1): DatanodeRegistration(0.0.0.0:50010, datanodeUuid=da77cef5-2125-42ee-87f6-1fbd6acf95ee, infoPort=50075, infoSecurePort=0, ipcPort=50020, storageInfo=lv=-56;cid=CID-2d669e73-96e6-4bbf-bb55-678919083f6c;nsid=1537263042;c=0)
        at org.apache.hadoop.hdfs.server.blockmanagement.DatanodeManager.registerDatanode(DatanodeManager.java:863)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.registerDatanode(FSNamesystem.java:4529)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.registerDatanode(NameNodeRpcServer.java:1279)
        at org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolServerSideTranslatorPB.registerDatanode(DatanodeProtocolServerSideTranslatorPB.java:95)
        at org.apache.hadoop.hdfs.protocol.proto.DatanodeProtocolProtos$DatanodeProtocolService$2.callBlockingMethod(DatanodeProtocolProtos.java:28539)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)
```

docker network ls
```
NETWORK ID          NAME                DRIVER              SCOPE
59c2345d9a13        bridge              bridge              local
467bec914ca8        hadoop              bridge              local
34205ed5a238        host                host                local
60150198b087        none                null                local
```

docker version
```
Client:
 Version:      17.11.0-ce-rc2
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:09:35 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce-rc2
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:12:05 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker-compose version
```
docker-compose version 1.15.0, build e12f3b9
docker-py version: 2.4.2
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
let me know if you need any other info!

**Comment by GezimSejdiu** [comment]
Hi @amalic ,
the docker configuration for running SANSA-RDF was listed here just at the beginning of the project. We did a bit of refactoring and we removed them from core SANSA Layers. 

For running SANSA functionalities, we do use of [SANSA-Examples](https://github.com/SANSA-Stack/SANSA-Examples) and for that, we provide a running environment on Docker aka [SANSA-Notebooks](https://github.com/SANSA-Stack/SANSA-Notebooks).

And for your own developed application using SANSA, you could have a look at [SANSA-RDF-Statistics](https://github.com/GezimSejdiu/Spark-RDF-Statistics) repo (soon will provide a more refined running example).

Best regards,

**Comment by GezimSejdiu** [comment]
Will close it for now! Will post more info on how to run a SANSA example using BDE docker images.
